version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install poetry
      - poetry config virtualenvs.in-project true
      - poetry install --with dev --no-root
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
