version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install poetry
      - poetry self add poetry-plugin-export
      - poetry export --output requirements.txt --with dev
      - pip install -r requirements.txt --no-deps
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
